<a href="https://colab.research.google.com/github/nageswar307/Python/blob/main/Descriptive%20Statisticsipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
{'numbers': np.arange(1, 101)}

{'numbers': array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100])}

In [ ]:
data = pd.DataFrame({'numbers': np.arange(1, 101),'numbers2':np.arange(101,201)})
sample = data.sample(n=20,random_state=42)
print(sample)
#data

    numbers  numbers2
83       84       184
53       54       154
70       71       171
45       46       146
44       45       145
39       40       140
22       23       123
80       81       181
10       11       111
0         1       101
18       19       119
30       31       131
73       74       174
33       34       134
90       91       191
4         5       105
76       77       177
77       78       178
12       13       113
31       32       132


In [ ]:
['dog']*60 + ['cat']*40

['dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'dog',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat',
 'cat']

In [ ]:
sample = df.sample(n=20)
print(sample)

   category
73      cat
1       dog
15      dog
58      dog
50      dog
72      cat
84      cat
57      dog
42      dog
24      dog
90      cat
56      dog
96      cat
5       dog
64      cat
4       dog
63      cat
59      dog
55      dog
52      dog


In [ ]:
7/20

0.35

In [ ]:
df = pd.DataFrame({'category': ['dog']*60 + ['cat']*40})
df.head()

category
0      dog
1      dog
2      dog
3      dog
4      dog

In [ ]:
from sklearn.model_selection import train_test_split
df = pd.DataFrame({'category': ['dog']*60 + ['cat']*40})
train, test = train_test_split(df, test_size=0.3, stratify=df['category'])
print(test['category'].value_counts())

category
dog    18
cat    12
Name: count, dtype: int64


In [ ]:
12/30

0.4

In [ ]:
k = 10
data.iloc[::k]

numbers
0         1
10       11
20       21
30       31
40       41
50       51
60       61
70       71
80       81
90       91

In [ ]:
k = 50
data = pd.DataFrame({'numbers': np.arange(1, 101)})
sample = data.iloc[::k]
print(sample)

    numbers
0         1
50       51


In [6]:
import numpy as np
import pandas as pd

In [4]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
data = pd.DataFrame({'value': np.arange(1, 101),"value2":np.arange(101,201)})
data.head(10)

value  value2
0      1     101
1      2     102
2      3     103
3      4     104
4      5     105
5      6     106
6      7     107
7      8     108
8      9     109
9     10     110

In [16]:
from sklearn.utils import resample
data = pd.DataFrame({'value': np.arange(1, 101)})
sample = resample(data, replace=True, n_samples=10, random_state=42)
print(sample)

    value
51     52
92     93
14     15
71     72
60     61
20     21
82     83
86     87
74     75
74     75


In [18]:
import tensorflow as tf
dataset = tf.data.Dataset.range(1000).batch(32)


In [19]:
dataset

<_BatchDataset element_spec=TensorSpec(shape=(None,), dtype=tf.int64, name=None)>

In [20]:
import tensorflow as tf
dataset = tf.data.Dataset.range(1000).batch(32)
for batch in dataset.take(1):
    print(batch.numpy())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]


In [1]:
from imblearn.over_sampling import SMOTE
import numpy as np

In [22]:
X = np.random.rand(100, 2)
X

array([[0.44427113, 0.8371924 ],
       [0.01601777, 0.26440663],
       [0.54129335, 0.13375121],
       [0.78872107, 0.42475621],
       [0.54437197, 0.95809791],
       [0.65276811, 0.48845439],
       [0.09335982, 0.23117491],
       [0.54276987, 0.5872614 ],
       [0.4139597 , 0.83472613],
       [0.90484268, 0.11295921],
       [0.25355625, 0.29817221],
       [0.27571083, 0.05617097],
       [0.60201795, 0.16672156],
       [0.9821431 , 0.07387174],
       [0.29243481, 0.63523761],
       [0.47643139, 0.14475823],
       [0.26129289, 0.30829255],
       [0.25056761, 0.91306697],
       [0.48205678, 0.87127005],
       [0.61100816, 0.00644134],
       [0.36035005, 0.14971707],
       [0.59937834, 0.57797789],
       [0.86689208, 0.6649637 ],
       [0.63958756, 0.75969777],
       [0.16191637, 0.36743899],
       [0.60612002, 0.05964801],
       [0.22403116, 0.52900601],
       [0.75590133, 0.56255925],
       [0.62735584, 0.35150653],
       [0.90837416, 0.65126085],
       [0.

In [23]:
[0]*90 + [1]*10

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [ ]:

X = np.random.rand(100, 2)
y = np.array([0]*90 + [1]*10)  # Imbalanced labels
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)
print(pd.Series(y_resampled).value_counts())  # Balanced classes

In [28]:
X = np.random.rand(100, 2)
y = np.array([0]*90 + [1]*10)  # Imbalanced labels

smote = SMOTE(random_state=42)
smote.fit_resample(X, y)
X_resampled, y_resampled = smote.fit_resample(X, y)
print(pd.Series(y_resampled).value_counts())

0    90
1    90
Name: count, dtype: int64


In [29]:
#Measures of central tendency
lst = [1,2,3,4,5,6,7,8,9,10]

mean = sum(lst)/len(lst)
mean

5.5

In [30]:
lst1 = [1,2,3,4,5,6,7,8,9,10,1000]
mean = sum(lst1)/len(lst1)
mean

95.9090909090909

In [34]:
income_lst = [10000,12000,14000,9000,12000,18000,10000,11000,15000,13000]
mean = sum(income_lst)/len(income_lst)
mean

12400.0

In [35]:
income_lst = [10000,12000,14000,9000,12000,18000,10000,11000,15000,13000,100000]
mean = sum(income_lst)/len(income_lst)
mean

20363.636363636364

In [45]:
#median
# sorting
income_lst = [10000,12000,14000,9000,12000,18000,10000,11000,15000,13000,100000]
income_lst = sorted(income_lst)
income_lst

[9000, 10000, 10000, 11000, 12000, 12000, 13000, 14000, 15000, 18000, 100000]

In [46]:
len(income_lst)/2

5.5

In [47]:
if len(income_lst)%2==0:
  income_lst[int(len(income_lst)/2)] + income_lst[int(len(income_lst)/2)-1]
  median = (income_lst[int(len(income_lst)/2)] + income_lst[int(len(income_lst)/2)-1])/2
else:
  median = income_lst[int(len(income_lst)/2)]
median

12000

In [ ]:
# variance
income_lst = [10000,12000,14000,9000,12000,18000,10000,11000,15000,13000]
mean = sum(income_lst)/len(income_lst)
mean

In [49]:
var = 0

for i in income_lst:
  var = var + (i-mean)**2

var = var/len(income_lst)
var

640231404.9586776

In [51]:
from math import sqrt

sqrt(var)

25302.794410078062

In [52]:
# percentile

income_lst = [10000,12000,14000,9000,12000,18000,10000,11000,15000,13000]
income_lst = sorted(income_lst)
income_lst

[9000, 10000, 10000, 11000, 12000, 12000, 13000, 14000, 15000, 18000]

In [53]:
7/10

0.7

In [54]:
10/10

1.0

In [58]:
import io
import pandas as pd
lst1 = pd.read_csv(io.StringIO('''
1200
1800
900
750
600
340
230
1200
'''), header=None)


In [59]:
import io
import pandas as pd
lst2 = pd.read_csv(io.StringIO('''
20000
400000
30000
120000
50000
30000
30000
30000
'''), header=None)


In [61]:
lst1 = list(lst1[0])
lst2 = list(lst2[0])
lst1,lst2

([1200, 1800, 900, 750, 600, 340, 230, 1200],
 [20000, 400000, 30000, 120000, 50000, 30000, 30000, 30000])

In [63]:
def calc_mean_and_sd(lst):
  mean = sum(lst)/len(lst)
  var = 0

  for i in income_lst:
    var = var + (i-mean)**2

  var = var/len(income_lst)
  sd = sqrt(var)
  return mean,sd


In [64]:
mean1,sd1 = calc_mean_and_sd(lst1)
mean2,sd2 = calc_mean_and_sd(lst2)

In [67]:
sd1/mean1

13.455403718271643

In [68]:
sd2/mean2

0.8607715107572989