<a href="https://colab.research.google.com/github/nageswar307/Python/blob/main/NP_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(12,dtype=np.float32).reshape(3,4)
arr3 = np.arange(16).reshape(2,4,2)
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [ ]:
# Array Attributes
#ndim
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
ndim = len(arr1.shape)
print(ndim)

1


In [ ]:
len(arr3.shape)

3

In [ ]:
#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(10,)
(3, 4)
(2, 4, 2)


In [ ]:
#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

10
12
16


In [ ]:
size = 1
for i in arr3.shape:
    size *= i
print(size)

16


In [ ]:
#itemsize
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

8
4
8


In [ ]:
#dtype
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
float32
int64


In [ ]:
# changing datatype

arr2 = arr2.astype(np.int32)
arr2.dtype

dtype('int32')

In [ ]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [ ]:
#changing shape

arr4 = np.arange(40).reshape(8,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr4.shape

(8, 5)

In [ ]:
#transpose
arr5 = arr4.T

In [ ]:
arr5.T.shape

(8, 5)

In [ ]:
lst = [1,2,3]
lst2 = lst
print(lst2)
lst2[0] = 4
print(lst2)
print(lst)
# print(lst2)

[1, 2, 3]
[4, 2, 3]
[4, 2, 3]


In [ ]:
a1 = np.array([1,2,3])
a2 = a1
print(a2)
a2[2] = 4
print(a2)
# print(a1)

[1 2 3]
[1 2 4]


In [ ]:
import numpy as np
x = np.arange(10)
# x
y = np.array([100,200])  # creates a view
# y
y[0:1] = [10, 11]
x
# y

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [2]:
import numpy as np

In [3]:
arr5 = np.arange(10).reshape(5,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
arr5.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#array operations
#scalar operations
#vector operations


In [ ]:
#scalar operations

In [11]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [13]:
arr1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [17]:
arr1==2

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
arr1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
arr1!=2

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
arr1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [21]:
arr1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [23]:
arr1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [25]:
#vector operations

In [24]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)

In [27]:
arr1,arr2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [26]:
arr1*arr2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [28]:
arr1-arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [29]:
arr1/arr2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [35]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,15).reshape(3,1)
arr1,arr2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12],
        [13],
        [14]]))

In [36]:
arr1+arr2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [37]:
#array functions

In [38]:
# min,max,sum,prod,floor,round,ceil,trigonometry,statistcs,log,exp

In [47]:
arr6 = np.arange(1,13).reshape(3,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
np.amax(arr6)

12

In [54]:
arr6.shape

(3, 4)

In [56]:
np.sum(arr6,axis=0) # columns -0 rows -1

78

In [59]:
np.prod(arr6,axis=1)

array([   24,  1680, 11880])

In [62]:
np.round(np.sqrt(arr6),3)

array([[1.   , 1.414, 1.732, 2.   ],
       [2.236, 2.449, 2.646, 2.828],
       [3.   , 3.162, 3.317, 3.464]])

In [63]:
np.floor(np.sqrt(arr6))

array([[1., 1., 1., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [64]:
np.ceil(np.sqrt(arr6))

array([[1., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 4., 4., 4.]])

In [66]:
np.cos(arr6)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [70]:
np.skewness(arr6)

AttributeError: module 'numpy' has no attribute 'skewness'

In [71]:
np.log(arr6)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [72]:
np.exp(arr6)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [74]:
#Indexing & Slicing

arr1 = np.arange(10)
arr2 = np.arange(12,dtype=np.float32).reshape(3,4)
arr3 = np.arange(16).reshape(2,4,2)
arr3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [76]:

arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr1[9]

9

In [79]:
arr1[0:4]

array([0, 1, 2, 3])

In [80]:
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [83]:
arr2[0][2]

2.0

In [ ]:
# arr[row,col]
# arr[start:end:stride,start:end:stride]

In [85]:
arr2[0:2,0:2]

array([[0., 1.],
       [4., 5.]], dtype=float32)

In [87]:
arr2[0:3:2,1:4:2]

array([[ 1.,  3.],
       [ 9., 11.]], dtype=float32)

In [90]:
arr2 = np.arange(12,dtype=np.float32).reshape(3,4)
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [89]:
arr2[1:3,:2]

array([[4., 5.],
       [8., 9.]], dtype=float32)

In [95]:
arr2[1:,1::2]

array([[ 5.,  7.],
       [ 9., 11.]], dtype=float32)

In [129]:
arr3 = np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
arr3[0:2,:,:1]

array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]]])

In [124]:
arr3[0][0:2,0:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
arr3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
arr3[0,:,0:1]

array([[0],
       [3],
       [6]])

In [131]:
arr3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [136]:
arr3[2,1:3,1:2]

array([[22],
       [25]])

In [137]:
arr3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [139]:
arr3[2,:,1:2]

array([[19],
       [22],
       [25]])

In [140]:
arr3[2,0:3,1:2]

array([[19],
       [22],
       [25]])

In [ ]:
# Fancy Indexing

In [141]:
arr2 = np.arange(12,dtype=np.float32).reshape(3,4)
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [142]:
arr2[:,[0,2,3]]

array([[ 0.,  2.,  3.],
       [ 4.,  6.,  7.],
       [ 8., 10., 11.]], dtype=float32)

In [148]:
arr2[[1,2]]

array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [156]:
arr2[[1,2],0:1]

array([[4.],
       [8.]], dtype=float32)

In [157]:
arr2[[1,2],0:1].shape

(2, 1)

In [158]:
#Boolean Indexing

arr3 = np.arange(27).reshape(3,3,3)
arr3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [160]:
arr3[arr3>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26])

In [163]:
arr3[arr3%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [173]:
arr3[(arr3>10) & (arr3%3==0)]

array([12, 15, 18, 21, 24])

In [174]:
# & for and
# | for or

In [ ]:
# functions
# indexing and slicing
