<a href="https://colab.research.google.com/github/nageswar307/Python/blob/main/NP_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
lst = [1,3.5,"string",[1,2,3]]

lst = [1,2,3,4,5]
lst = [1.2,3.4,2.5,6.7]
lst = ["a","d","w"]



In [2]:
# lists are ordered collection of heterogenous items
# numpy arrays are ordered collection of homogenous items

In [5]:
# list(range(size))

In [3]:
size = 1000

lst1 = list(range(size))
lst2 = list(range(size))

In [7]:
import numpy as np

In [8]:
arr1 = np.arange(size)
arr2 = np.arange(size)

In [10]:
lst1=[1,2,3]
lst2=[1,2,3] #[1+1,2+2,3+3] [2,4,6]

In [11]:
lst1+lst2

[1, 2, 3, 1, 2, 3]

In [13]:
output = []
for i in range(len(lst1)):
  output.append(lst1[i]+lst2[i])
    # print(lst1[i]+lst2[i])

In [14]:
output

[2, 4, 6]

In [16]:
output = [x+y for x,y in zip(lst1,lst2)]
output

[2, 4, 6]

In [18]:
size = 1000

lst1 = list(range(size))
lst2 = list(range(size))

arr1 = np.arange(size)
arr2 = np.arange(size)

In [19]:
import timeit

In [20]:
%timeit [x+y for x,y in zip(lst1,lst2)]


45.5 µs ± 854 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
%timeit arr1+arr2

1.24 µs ± 350 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
nested_list = [[1,2,3],[4,5,6]]

In [ ]:
# Key features of Numpy

# N-Dimensional array -  ndarray
# Vectorization
# Broadcasting
# Mathematical functions
# Random Module

In [25]:
# creating numpy arrays

arr1 = np.array([1,2,3,"abc"])

In [31]:
arr1.dtype

dtype('<U21')

In [33]:
arr2 = np.array((1,2,3,4,5,6,"abc"))
arr2.dtype

dtype('<U21')

In [30]:
arr3 = np.arange(1,100,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [36]:
arr4 = np.linspace(0,10,5)
arr4

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
arr4 = np.linspace(0,100,5)
arr4

array([  0.,  25.,  50.,  75., 100.])

In [58]:
arr5 = np.zeros((5,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
arr6 = np.ones((5,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
arr7 = np.eye(6,5)
arr7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [50]:
arr8 = np.full((5,3),5)
arr8

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [60]:
arr9 = np.random.random((5,3))
arr9

array([[0.67581188, 0.97610173, 0.21216721],
       [0.70238495, 0.67251557, 0.98502154],
       [0.85474657, 0.7189817 , 0.8156991 ],
       [0.87660123, 0.95943831, 0.56074636],
       [0.4396171 , 0.82987495, 0.23746026]])

In [62]:
arr10 = np.random.randint(-100,100,(5,3))
arr10

array([[-44,  35,  10],
       [-78, -92,  31],
       [-82, -42, -58],
       [ -5, -20, -31],
       [ 77,   8, -51]])

In [63]:
arr11 = np.random.randn(5,3)
arr11

array([[ 0.74162282,  0.19626611, -1.35638148],
       [ 0.95639218,  0.04548583, -0.82233954],
       [ 0.83959934,  0.99607309, -0.0790971 ],
       [ 0.3090566 ,  1.47469395, -1.26684832],
       [-1.05762353, -0.21496344, -0.89538432]])

In [65]:
arr12 = np.random.rand(3,3)
arr12

array([[0.77301143, 0.3017427 , 0.77214152],
       [0.35437696, 0.1573893 , 0.98214979],
       [0.01716261, 0.0373725 , 0.67615833]])

In [68]:
arr13 = np.empty((3,3))
arr13

array([[0.48023839, 0.41919757, 0.60552487],
       [0.84323113, 0.59230088, 0.42360803],
       [0.14355699, 0.81264647, 0.98778562]])